export const moduleConfigs = [
  {
    key: 'familyMembers',
    label: 'Family Members',
    path: '/family',
    apiPath: '/family',
    implemented: true,
  },
  {
    key: 'vehicles',
    label: 'Vehicles',
    path: '/vehicle',
    apiPath: '/vehicle',
    familyMemberField: 'owner',
    ownerNameKey: 'ownerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'model', label: 'Model' },
      { key: 'registrationNumber', label: 'Reg. Number' },
      { key: 'ownerName', label: 'Owner' },
    ],
    formFields: [
      { key: 'type', label: 'Type', type: 'text', required: true, placeholder: 'Car, Bike, etc.' },
      { key: 'model', label: 'Model', type: 'text', required: true, placeholder: 'Honda City' },
      { key: 'registrationNumber', label: 'Registration Number', type: 'text', required: true },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['type', 'model', 'registrationNumber', 'ownerName'],
  },
  {
    key: 'investments',
    label: 'Investments',
    path: '/investment',
    apiPath: '/investment',
    familyMemberField: 'holder',
    ownerNameKey: 'holderName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'name', label: 'Name' },
      { key: 'institution', label: 'Institution' },
      { key: 'investedAmount', label: 'Invested' },
      { key: 'currentValue', label: 'Current Value' },
      { key: 'maturityDate', label: 'Maturity Date' },
      { key: 'holderName', label: 'Holder' },
    ],
    formFields: [
      { key: 'type', label: 'Type', type: 'text', required: true, placeholder: 'MutualFund, FD, Stock, PPF, NPS' },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'institution', label: 'Institution', type: 'text' },
      { key: 'investedAmount', label: 'Invested Amount', type: 'number', required: true },
      { key: 'currentValue', label: 'Current Value', type: 'number' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'maturityDate', label: 'Maturity Date', type: 'date' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['type', 'name', 'institution', 'holderName'],
  },
  {
    key: 'insurances',
    label: 'Insurances',
    path: '/insurance',
    apiPath: '/insurance',
    familyMemberField: 'holder',
    ownerNameKey: 'holderName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'policyNumber', label: 'Policy No.' },
      { key: 'provider', label: 'Provider' },
      { key: 'premiumAmount', label: 'Premium' },
      { key: 'sumAssured', label: 'Sum Assured' },
      { key: 'expiryDate', label: 'Expiry' },
      { key: 'holderName', label: 'Holder' },
    ],
    formFields: [
      { key: 'type', label: 'Type', type: 'text', required: true, placeholder: 'Life, Health, Vehicle, Home' },
      { key: 'policyNumber', label: 'Policy Number', type: 'text', required: true },
      { key: 'provider', label: 'Provider', type: 'text', required: true },
      { key: 'premiumAmount', label: 'Premium Amount', type: 'number', required: true },
      { key: 'sumAssured', label: 'Sum Assured', type: 'number' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['type', 'policyNumber', 'provider', 'holderName'],
  },
  {
    key: 'medicalRecords',
    label: 'Medical Records',
    path: '/medical-record',
    apiPath: '/medical-record',
    familyMemberField: 'member',
    ownerNameKey: 'memberName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'title', label: 'Title' },
      { key: 'doctorName', label: 'Doctor' },
      { key: 'hospitalName', label: 'Hospital' },
      { key: 'recordDate', label: 'Date' },
      { key: 'memberName', label: 'Member' },
    ],
    formFields: [
      { key: 'type', label: 'Type', type: 'text', required: true, placeholder: 'Diagnosis, Prescription, Lab Report, Vaccination' },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'doctorName', label: 'Doctor Name', type: 'text' },
      { key: 'hospitalName', label: 'Hospital Name', type: 'text' },
      { key: 'recordDate', label: 'Record Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'text' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['type', 'title', 'doctorName', 'hospitalName', 'memberName'],
  },
  {
    key: 'properties',
    label: 'Properties',
    path: '/property',
    apiPath: '/property',
    familyMemberField: 'owner',
    ownerNameKey: 'ownerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'address', label: 'Address' },
      { key: 'city', label: 'City' },
      { key: 'purchaseValue', label: 'Purchase Value' },
      { key: 'currentValue', label: 'Current Value' },
      { key: 'isRented', label: 'Rented?' },
      { key: 'ownerName', label: 'Owner' },
    ],
    formFields: [
      { key: 'type', label: 'Type', type: 'text', required: true, placeholder: 'House, Apartment, Plot, Commercial' },
      { key: 'address', label: 'Address', type: 'text', required: true },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'purchaseDate', label: 'Purchase Date', type: 'date' },
      { key: 'purchaseValue', label: 'Purchase Value', type: 'number', required: true },
      { key: 'currentValue', label: 'Current Value', type: 'number' },
      { key: 'isRented', label: 'Is Rented?', type: 'boolean' },
      { key: 'rentalIncome', label: 'Monthly Rental Income', type: 'number' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['type', 'address', 'city', 'state', 'ownerName'],
  },
  {
    key: 'bankAccounts',
    label: 'Bank Accounts',
    path: '/bank-account',
    apiPath: '/bank-account',
    familyMemberField: 'owner',
    ownerNameKey: 'ownerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'accountType', label: 'Type' },
      { key: 'bankName', label: 'Bank' },
      { key: 'accountNumber', label: 'Account No.' },
      { key: 'ifscCode', label: 'IFSC' },
      { key: 'balance', label: 'Balance' },
      { key: 'ownerName', label: 'Owner' },
    ],
    formFields: [
      { key: 'accountType', label: 'Account Type', type: 'text', required: true, placeholder: 'Savings, Current, FD' },
      { key: 'bankName', label: 'Bank Name', type: 'text', required: true },
      { key: 'accountNumber', label: 'Account Number', type: 'text', required: true },
      { key: 'ifscCode', label: 'IFSC Code', type: 'text' },
      { key: 'branchName', label: 'Branch Name', type: 'text' },
      { key: 'balance', label: 'Balance', type: 'number' },
      { key: 'openedDate', label: 'Opened Date', type: 'date' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['accountType', 'bankName', 'accountNumber', 'ownerName'],
  },
  {
    key: 'contacts',
    label: 'Contacts',
    path: '/contact',
    apiPath: '/contact',
    familyMemberField: 'addedBy',
    ownerNameKey: 'addedByName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'organization', label: 'Organization' },
      { key: 'addedByName', label: 'Added By' },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text', required: true, placeholder: 'Doctor, Lawyer, Emergency, etc.' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'organization', label: 'Organization', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
      { key: 'familyMemberId', label: 'Added By (Family Member)', type: 'familySelect', required: true },
    ],
    searchKeys: ['name', 'category', 'phone', 'organization', 'addedByName'],
  },
  {
    key: 'subscriptions',
    label: 'Subscriptions',
    path: '/subscription',
    apiPath: '/subscription',
    familyMemberField: 'owner',
    ownerNameKey: 'ownerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'amount', label: 'Amount' },
      { key: 'billingCycle', label: 'Billing' },
      { key: 'renewalDate', label: 'Renewal Date' },
      { key: 'isActive', label: 'Active' },
      { key: 'ownerName', label: 'Owner' },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text', required: true, placeholder: 'OTT, Music, Fitness, Software' },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'billingCycle', label: 'Billing Cycle', type: 'select', options: ['Monthly', 'Quarterly', 'Yearly'], required: true },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'renewalDate', label: 'Renewal Date', type: 'date' },
      { key: 'isActive', label: 'Active?', type: 'boolean' },
      { key: 'notes', label: 'Notes', type: 'text' },
      { key: 'familyMemberId', label: 'Family Member', type: 'familySelect', required: true },
    ],
    searchKeys: ['name', 'category', 'billingCycle', 'ownerName'],
  },
  {
    key: 'loans',
    label: 'Loans',
    path: '/loan',
    apiPath: '/loan',
    familyMemberField: 'borrower',
    ownerNameKey: 'borrowerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'loanType', label: 'Type' },
      { key: 'bankName', label: 'Bank' },
      { key: 'principalAmount', label: 'Principal' },
      { key: 'outstandingAmount', label: 'Outstanding' },
      { key: 'emiAmount', label: 'EMI' },
      { key: 'status', label: 'Status' },
      { key: 'borrowerName', label: 'Borrower' },
    ],
    formFields: [
      { key: 'loanType', label: 'Loan Type', type: 'text', required: true, placeholder: 'Home, Personal, Vehicle, Education' },
      { key: 'bankName', label: 'Bank Name', type: 'text', required: true },
      { key: 'accountNumber', label: 'Account Number', type: 'text' },
      { key: 'principalAmount', label: 'Principal Amount', type: 'number', required: true },
      { key: 'outstandingAmount', label: 'Outstanding Amount', type: 'number' },
      { key: 'interestRate', label: 'Interest Rate (%)', type: 'number', required: true },
      { key: 'emiAmount', label: 'EMI Amount', type: 'number' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Closed', 'Overdue'], required: true },
      { key: 'familyMemberId', label: 'Borrower (Family Member)', type: 'familySelect', required: true },
    ],
    searchKeys: ['loanType', 'bankName', 'status', 'borrowerName'],
  },
  {
    key: 'documents',
    label: 'Documents',
    path: '/document',
    apiPath: '/document',
    ownerNameKey: 'ownerName',
    tableColumns: [
      { key: 'id', label: 'ID' },
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type' },
      { key: 'expiryDate', label: 'Expiry Date' },
      { key: 'ownerName', label: 'Owner' },
    ],
    formFields: [],
    searchKeys: ['title', 'type', 'ownerName'],
    uploadOnly: true,
  },
]

